
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: de-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"


  sensor-simulator:
    build:
      context: ..
      dockerfile: docker/Dockerfile.sensor_simulator
    container_name: de-sensor-simulator
    depends_on:
      - kafka
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=de-kafka:9092  # "de-kafka" statt "localhost"
    restart: unless-stopped
    networks:
      - default

  stream-processor:
    build:
      context: ..
      dockerfile: docker/Dockerfile.stream_processing
    container_name: de-stream-processor
    depends_on:
      - kafka
      - postgres
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=de-kafka:9092
      - PG_HOST=de-postgres  # "de-postgres" statt "localhost"
      - PG_PORT=5432
      - PG_DB=de_db
      - PG_USER=de_user
      - PG_PASSWORD=de_password
    restart: unless-stopped
    networks:
      - default


  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: de-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://de-kafka:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: postgres:16-alpine
    container_name: de-postgres
    environment:
      POSTGRES_USER: de_user
      POSTGRES_PASSWORD: de_password
      POSTGRES_DB: de_db
    ports:
      - "5432:5432"
    volumes:
      - de-postgres-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql


  grafana:
    image: grafana/grafana:latest
    container_name: de-grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - postgres



volumes:
  de-postgres-data:

  
