apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: de-postgres:5432
    database: de_db
    user: de_user
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: 'de_password'
    isDefault: true
    editable: false
